1.DATA CREATION:Create a suitable arrays to represent students,subjects,and their marks

In [1]:
import numpy as np
scl = np.array([[101,102,103,104],[1321,2432,3543,4654],[67,98,87,35]])
scl

array([[ 101,  102,  103,  104],
       [1321, 2432, 3543, 4654],
       [  67,   98,   87,   35]])

2.DATA EXPLORATION:explore the properties of these arrays,such as their dimension,size and structure

In [3]:
scl.shape
scl.ndim
scl.size

12

3.DATA TRANSFORMATION:perform necessary reshaping and regognising of the data to suit various operations

In [2]:
scl.T

array([[ 101, 1321,   67],
       [ 102, 2432,   98],
       [ 103, 3543,   87],
       [ 104, 4654,   35]])

4.DATA COMBINATION:merge or split arrays to stimulate adding new students,nwe subjects,or recognaising the datasets

In [4]:
newcol = np.array([[109],[9879],[58]])
scl = np.hstack((scl,newcol))
scl

array([[ 101,  102,  103,  104,  109],
       [1321, 2432, 3543, 4654, 9879],
       [  67,   98,   87,   35,   58]])

5.DATA MODIFICATION:Apply operations to update marks,remove data,or identify unique information

In [7]:
student = scl[0]
subject = scl[1]
marks = scl[2]

marks[3]=89
marks[2]=56

np.delete(subject,4)

subject

marks

array([67, 98, 56, 89, 58])

In [8]:
data = np.array([student,subject,marks])
data

array([[ 101,  102,  103,  104,  109],
       [1321, 2432, 3543, 4654, 9879],
       [  67,   98,   56,   89,   58]])

6.DATA TYPE HANDLING:Demonstrate howthe same data can exists in different data types and how changes affect results

In [9]:
nscl=scl.copy()
nscl[0][3]=108
nscl
'''array([[ 101,  102,  103,  104,  107,  108,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''
scl
'''array([[ 101,  102,  103,  104,  107,  107,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''

scl

array([[ 101,  102,  103,  104,  109],
       [1321, 2432, 3543, 4654, 9879],
       [  67,   98,   56,   89,   58]])

7.COPY AND VIEW BEHAVIOUR:Show the difference between creating a full copy of array and creating a view of the same data.

In [10]:
vscl = scl.view()
vscl[1][4]=8978
vscl
'''array([[ 101,  102,  103,  104,  107,  107,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''
scl
'''array([[ 101,  102,  103,  104,  107,  107,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''
scl

array([[ 101,  102,  103,  104,  109],
       [1321, 2432, 3543, 4654, 8978],
       [  67,   98,   56,   89,   58]])